#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  Author: Adrian Böckenkamp
# License: BSD (https://opensource.org/licenses/BSD-3-Clause)
#    Date: 08/06/2017
#
# TODO list:
# - allow adding additional env. variables to generated env-loader via API
# - complete documentation

if __name__ == '__main__':
    from roslaunch2 import main as roslaunch2_main
    roslaunch2_main()
