#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  Author: Adrian Böckenkamp
# License: BSD (https://opensource.org/licenses/BSD-3-Clause)
#    Date: 15/02/2017

if __name__ == '__main__':
    from roslaunch2 import main as roslaunch2_main
    roslaunch2_main()
